name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set MONGO_URI in Environment
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: env | grep MONGO_URI

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Run Streamlit App
        run: streamlit run app/streamlit_app.py --server.port 8501 --server.headless true
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
